<?php
session_start();
require('lib/fpdf.php');

class PDF extends FPDF
{
    function Header()
    {
        // Blue header box
        $this->SetFillColor(66, 103, 178); // CareGuides blue
        $this->Rect(10, 10, 190, 30, 'F');

        // White text inside header
        $this->SetXY(15, 14);
        $this->SetTextColor(255, 255, 255);
        $this->SetFont('Arial', 'B', 14);
        $this->Cell(0, 6, 'CareGuides - Autism Screening Report', 0, 1);

        $this->SetX(15);
        $this->SetFont('Arial', '', 10);
        $this->Cell(0, 6, 'Email: support@careguides.com | Phone: 555-543-5432', 0, 1);

        $this->SetX(15);
        $this->Cell(0, 6, 'Website: www.careguides.com | Address: 5432 Street West, Townsville, State 54321', 0, 1);

        $this->Ln(5);
    }

    function Footer()
    {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->SetTextColor(150, 150, 150);
        $this->Cell(0, 10, 'Report generated by CareGuides | Page ' . $this->PageNo() . '/{nb}', 0, 0, 'C');
    }
}

$pdf = new PDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetFont('Arial', '', 12);
$pdf->SetTextColor(0, 0, 0);

// Letter-like introduction
$pdf->Ln(10);
$pdf->MultiCell(0, 8, "Dear Parent,\n\nWe are pleased to provide you with the results of the developmental screening questionnaire completed for your child. This report is intended to assist in early detection and understanding of autism spectrum behaviors.");

$pdf->Ln(5);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 10, "Child's Name: " . $_SESSION['name'], 0, 1);
$pdf->SetFont('Arial', '', 12);

// Questions
$questions = [
    "A1: Does the child look at you when you call his/her name?",
    "A2: Does the child point at objects to show interest?",
    "A3: Does the child pretend play (e.g., pretend to drink from an empty cup)?",
    "A4: Does the child use single words meaningfully?",
    "A5: Does the child respond to their name?",
    "A6: Does the child make eye contact when interacting?",
    "A7: Does the child show interest in other children?",
    "A8: Does the child bring objects to show parents?",
    "A9: Does the child follow simple instructions?",
    "A10: Does the child engage in back-and-forth social interaction?"
];

$pdf->Ln(5);
foreach ($questions as $i => $q) {
    $answer = $_SESSION["a" . ($i + 1)] == 0 ? "Yes" : "No";
    $pdf->MultiCell(0, 8, $q . "  Answer: " . $answer);
}

$pdf->Ln(10);
$result = $_SESSION['res'] == 1
    ? "Possible signs of autism were detected. We recommend consulting a developmental specialist for further evaluation."
    : "Based on the questionnaire responses, your child is unlikely to show signs of autism.";

$pdf->SetFont('Arial', 'B', 12);
$pdf->MultiCell(0, 10, "Result: " . $result);

$pdf->Ln(15);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(0, 10, '_________________________', 0, 1, 'L');
$pdf->Cell(0, 5, 'Parent/Guardian Signature', 0, 1, 'L');

$pdf->Output('D', 'Autism_Report.pdf');
exit;
